# Generated by Django 2.0.4 on 2018-05-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siklinik', '0002_auto_20180506_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='wilayah',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='wilayah',
        ),
    ]
