# Generated by Django 2.0.4 on 2018-05-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siklinik', '0003_auto_20180506_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='kelpas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='siklinik.Kelompok_Pasien'),
        ),
    ]
