# Generated by Django 2.0.4 on 2018-05-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siklinik', '0005_remove_pasien_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='email',
        ),
    ]
